apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: gp2          # In-tree AWS EBS provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
