apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim   # PVC name
  labels:
    app: vprodb
spec:
  storageClassName: default # asks Kubernetes to use the "default" StorageClass
  accessModes:
    - ReadWriteOnce           # one node can mount it read/write at a time
  resources:
    requests:
      storage: 2Gi            # asking for 2 GiB of storage
